# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ccbada9a69010962a0c6a5d412713e63b6306d4a0b00941d52d5041b827ed6dbf13e5220a3749fa539ee474d039efc84a645a166b07883d86fa0136b0cbaa3b

test:
  secret_key_base: 8f106e836662399effc30212253a932973d31e5757c2054c51869c9eb7682cfc1ff30f2d7c06e27709f30c2aa80a2b5441fbe8856136e266f1910b6e65685ce8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
